import { AchievementRarity, AchievementStatus, AchievementTriggerType } from './types.ts';

export interface SeedAchievement {
  slug: string;
  title: string;
  description: string;
  icon: string;
  rarity: AchievementRarity;
  status: AchievementStatus;
  badgeStyle: string;
  conditionType: AchievementTriggerType;
  conditionConfig: Record<string, any>;
  isSecret?: boolean;
  points: number;
}

export const SEED_ACHIEVEMENTS: SeedAchievement[] = [
  // 1. Account & Identity
  {
    slug: 'welcome',
    title: 'Добро пожаловать в Dodik Tracker',
    description: 'Успешная регистрация личного аккаунта в сервисе.',
    icon: 'Sparkles',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'USER_REGISTERED',
    conditionConfig: { count: 1 },
    points: 10,
  },
  {
    slug: 'verified-account',
    title: 'Подтверждённый профиль',
    description: 'Указан и верифицирован email для защиты аккаунта.',
    icon: 'ShieldCheck',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'emerald',
    conditionType: 'USER_VERIFIED',
    conditionConfig: { count: 1 },
    points: 15,
  },

  // 2. Movies
  {
    slug: 'first-movie-added',
    title: 'Первый сеанс',
    description: 'Добавлен первый фильм в личную библиотеку.',
    icon: 'Film',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'blue',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'MOVIE', count: 1 },
    points: 10,
  },
  {
    slug: 'first-movie-watched',
    title: 'Киноман-новичок',
    description: 'Посмотрен и отмечен первый фильм.',
    icon: 'CheckCircle2',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'MOVIE', status: 'COMPLETED', count: 1 },
    points: 15,
  },
  {
    slug: 'movies-watched-10',
    title: 'Завсегдатай кинозала',
    description: 'Посмотрено 10 фильмов.',
    icon: 'Clapperboard',
    rarity: 'UNCOMMON',
    status: 'ACTIVE',
    badgeStyle: 'blue',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'MOVIE', status: 'COMPLETED', count: 10 },
    points: 30,
  },
  {
    slug: 'movies-watched-50',
    title: 'Настоящий синефил',
    description: 'Посмотрено 50 фильмов.',
    icon: 'Award',
    rarity: 'RARE',
    status: 'ACTIVE',
    badgeStyle: 'indigo',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'MOVIE', status: 'COMPLETED', count: 50 },
    points: 75,
  },
  {
    slug: 'movies-watched-100',
    title: 'Магистр кинематографа',
    description: 'Посмотрено 100 фильмов.',
    icon: 'Crown',
    rarity: 'EPIC',
    status: 'ACTIVE',
    badgeStyle: 'amber',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'MOVIE', status: 'COMPLETED', count: 100 },
    points: 150,
  },
  {
    slug: 'movies-watched-500',
    title: 'Живая легенда экрана',
    description: 'Посмотрено 500 фильмов. Абсолютное погружение в мировое кино.',
    icon: 'Flame',
    rarity: 'LEGENDARY',
    status: 'ACTIVE',
    badgeStyle: 'rose',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'MOVIE', status: 'COMPLETED', count: 500 },
    points: 500,
  },

  // 3. TV Series
  {
    slug: 'first-tv-added',
    title: 'Пилотный эпизод',
    description: 'Добавлен первый сериал в библиотеку.',
    icon: 'Tv',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'cyan',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'TV', count: 1 },
    points: 10,
  },
  {
    slug: 'first-tv-completed',
    title: 'Финальные титры',
    description: 'Полностью завершён просмотр первого сериала.',
    icon: 'Tv2',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'TV', status: 'COMPLETED', count: 1 },
    points: 20,
  },

  // 4. Anime & Manga
  {
    slug: 'first-anime-added',
    title: 'Отаку в душе',
    description: 'Добавлено первое аниме в библиотеку.',
    icon: 'Sparkles',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'rose',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'ANIME', count: 1 },
    points: 10,
  },
  {
    slug: 'anime-completed-10',
    title: 'Повелитель тайтлов',
    description: 'Завершено 10 аниме-сериалов или фильмов.',
    icon: 'Flame',
    rarity: 'RARE',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'ANIME', status: 'COMPLETED', count: 10 },
    points: 50,
  },
  {
    slug: 'first-manga-added',
    title: 'Читатель свитков',
    description: 'Добавлена первая манга в трекер.',
    icon: 'BookOpen',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'emerald',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'MANGA', count: 1 },
    points: 10,
  },

  // 5. Games
  {
    slug: 'first-game-added',
    title: 'Press Start',
    description: 'Добавлена первая видеоигра в библиотеку.',
    icon: 'Gamepad2',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'emerald',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'GAME', count: 1 },
    points: 10,
  },
  {
    slug: 'first-game-completed',
    title: 'Game Over: Victory',
    description: 'Пройдена первая видеоигра.',
    icon: 'Trophy',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'amber',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'GAME', status: 'COMPLETED', count: 1 },
    points: 20,
  },
  {
    slug: 'games-completed-10',
    title: 'Хардкорный геймер',
    description: 'Пройдено 10 видеоигр.',
    icon: 'Zap',
    rarity: 'RARE',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'GAME', status: 'COMPLETED', count: 10 },
    points: 60,
  },

  // 6. Books & Music
  {
    slug: 'first-book-added',
    title: 'Первая страница',
    description: 'Добавлена первая книга в библиотеку.',
    icon: 'Book',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'blue',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'BOOK', count: 1 },
    points: 10,
  },
  {
    slug: 'first-book-read',
    title: 'Книжный червь',
    description: 'Прочитана и отмечена первая книга.',
    icon: 'BookMarked',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'amber',
    conditionType: 'MEDIA_COMPLETED',
    conditionConfig: { mediaType: 'BOOK', status: 'COMPLETED', count: 1 },
    points: 20,
  },
  {
    slug: 'first-music-added',
    title: 'Меломан',
    description: 'Добавлен первый музыкальный альбом или трек.',
    icon: 'Music',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'rose',
    conditionType: 'MEDIA_ADDED',
    conditionConfig: { mediaType: 'MUSIC', count: 1 },
    points: 10,
  },

  // 7. Reviews & Social
  {
    slug: 'first-review',
    title: 'Первая рецензия',
    description: 'Опубликован первый отзыв на медиа-контент.',
    icon: 'MessageSquare',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'REVIEW_WRITTEN',
    conditionConfig: { count: 1 },
    points: 15,
  },
  {
    slug: 'reviews-10',
    title: 'Глас народа',
    description: 'Написано и опубликовано 10 содержательных отзывов.',
    icon: 'FileText',
    rarity: 'UNCOMMON',
    status: 'ACTIVE',
    badgeStyle: 'blue',
    conditionType: 'REVIEW_WRITTEN',
    conditionConfig: { count: 10 },
    points: 40,
  },
  {
    slug: 'first-like-received',
    title: 'Первое признание',
    description: 'Получен первый лайк от другого пользователя.',
    icon: 'Heart',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'rose',
    conditionType: 'LIKE_RECEIVED',
    conditionConfig: { count: 1 },
    points: 10,
  },
  {
    slug: 'likes-received-10',
    title: 'Звезда сообщества',
    description: 'Получено 10 лайков за рецензии и подборки.',
    icon: 'Sparkles',
    rarity: 'RARE',
    status: 'ACTIVE',
    badgeStyle: 'amber',
    conditionType: 'LIKE_RECEIVED',
    conditionConfig: { count: 10 },
    points: 50,
  },
  {
    slug: 'first-friend',
    title: 'Вместе веселее',
    description: 'Добавлен первый друг в Dodik Tracker.',
    icon: 'Users',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'emerald',
    conditionType: 'FRIEND_ADDED',
    conditionConfig: { count: 1 },
    points: 15,
  },

  // 8. Custom Lists & Tier Lists
  {
    slug: 'first-list-created',
    title: 'Куратор контента',
    description: 'Создан первый персональный список подборок.',
    icon: 'ListOrdered',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'LIST_CREATED',
    conditionConfig: { count: 1 },
    points: 15,
  },
  {
    slug: 'list-10-items',
    title: 'Солидная коллекция',
    description: 'В список добавлено 10 или более элементов.',
    icon: 'Layers',
    rarity: 'UNCOMMON',
    status: 'ACTIVE',
    badgeStyle: 'blue',
    conditionType: 'LIST_ITEM_ADDED',
    conditionConfig: { minItems: 10 },
    points: 25,
  },
  {
    slug: 'first-tier-list-created',
    title: 'Мастер ранжирования',
    description: 'Создан первый Tier List в Dodik Tracker.',
    icon: 'LayoutGrid',
    rarity: 'COMMON',
    status: 'ACTIVE',
    badgeStyle: 'amber',
    conditionType: 'TIER_LIST_CREATED',
    conditionConfig: { count: 1 },
    points: 20,
  },
  {
    slug: 'tier-list-filled',
    title: 'Идеальная расстановка',
    description: 'Заполнен и сохранён Tier List с элементами по тирам.',
    icon: 'BarChart3',
    rarity: 'UNCOMMON',
    status: 'ACTIVE',
    badgeStyle: 'purple',
    conditionType: 'TIER_LIST_COMPLETED',
    conditionConfig: { count: 1, requireFilled: true },
    points: 30,
  },

  // 9. Streaks
  {
    slug: 'streak-3-days',
    title: 'Верный трекер',
    description: 'Активность в сервисе в течение 3 дней подряд.',
    icon: 'Calendar',
    rarity: 'UNCOMMON',
    status: 'ACTIVE',
    badgeStyle: 'emerald',
    conditionType: 'DAYS_STREAK',
    conditionConfig: { days: 3 },
    points: 30,
  },
  {
    slug: 'streak-7-days',
    title: 'Неделя преданности',
    description: 'Ежедневная активность в течение 7 дней подряд.',
    icon: 'Flame',
    rarity: 'RARE',
    status: 'ACTIVE',
    badgeStyle: 'rose',
    conditionType: 'DAYS_STREAK',
    conditionConfig: { days: 7 },
    points: 70,
  },

  // 10. Secret
  {
    slug: 'secret-pioneer',
    title: 'Тайный первопроходец',
    description: 'Вы нашли скрытую грань Dodik Tracker.',
    icon: 'EyeOff',
    rarity: 'SECRET',
    status: 'HIDDEN',
    badgeStyle: 'indigo',
    conditionType: 'CUSTOM',
    conditionConfig: { customKey: 'secret_trigger', targetValue: 1 },
    isSecret: true,
    points: 100,
  },
];
